node {
        checkout scm
        stage('Build') {
            docker.image('python:3.12.1-alpine3.19').inside {
                sh 'python -m py_compile sources/add2vals.py sources/calc.py'
                stash name: 'compiled-results', includes: 'sources/*.py*'
            }
        }

        stage('Test') {
            try {
	             docker.image('qnib/pytest').inside {
                    sh 'py.test --junit-xml test-reports/results.xml sources/test_calc.py'
                }
            } catch (e) {
                    echo "Test Stage Failed!"
            } finally {
                junit 'test-reports/results.xml'
            }
        }

        stage('Manual Approval') {
            input message: 'Proceed to deploy stage?', ok: 'Yes'
        }

        stage('Deploy') {
            env.VOLUME = "${pwd()}/sources:/src"
            env.IMAGE = 'cdrx/pyinstaller-linux:python2'

            dir("${env.BUILD_ID}") {
                unstash 'compiled-results'
                sh "docker run --rm -v ${env.VOLUME} ${env.IMAGE} 'pyinstaller -F add2vals.py'"
            }

            archiveArtifacts "sources/dist/add2vals"
            sh "ssh-keyscan -H 3.26.235.211 >> ~/.ssh/known_hosts"
	        sh "/usr/bin/scp -i /home/jenkins/remote-home.pem /var/jenkins_home/workspace/submission-cicd-pipeline-agungfazr/sources/dist/add2vals  ubuntu@3.26.235.211:/home/ubuntu/add2vals"
            sh 'ssh -i /home/jenkins/remote-home.pem ubuntu@3.26.235.211 "cd /home/ubuntu && ./add2vals 4 4"'
            
            sleep 60
        }
}
